### PR TITLE
bare minimum update to build for python3

### PR DESCRIPTION
**Pull request by jalavosus**
modified print statements to print functions. Builds fine on my machine.

### CODE REVIEW

**Comment by AdamMJenks** [comment]
Hey James,

We're actually going to make a separate 2.7 and 3.0 builds for python stattleship.  So in the next couple of days i'm going to make a new python 3 repo which you can commit your changes to.  Does this sound good?

**Comment by jalavosus** [comment]
Adam,

Thanks for the heads up! I'll keep an eye out for it.

## 

James

**Comment by dthyresson** [comment]
@AdamMJenks Let's keep a single repository, but maintain separate branches - a 2.7 and 3.0.

`master` should be the current branch in development.

Having two repo's will make it much more difficult to merge in changes as well as keep the functionality similar.

I know i have Python 2.7 by default on my mac, so would the be the version most people would use?

**Comment by AdamMJenks** [comment]
My fault, I was thinking in my head two branches (not two repos).  It depends, most people I know still use 2.7 as there has never been a hard conversion

**Comment by jalavosus** [comment]
According to 2to3 (output [here](http://pastebin.com/YAmG1X3z)), the changes aren't that difficult. I can make the changes if you have a branch I can make pull requests to.

**Comment by AdamMJenks** [comment]
I just made a Stattleship-Python(v3) branch if you wanted to pull off of that branch

**Pull request closed without merging**
