### PR TITLE
Make installable with pip

### PR DESCRIPTION
**Pull request by drewpinta**

### CODE REVIEW

**Comment by dthyresson** [comment]
Hi @drewpinta.

Thanks for the PR.

@AdamMJenks could you review as part of your pending PR and if all good we'll merge?

**Comment by dthyresson** [comment]
@drewpinta We merged in a PR and there is a conflict. Could rebase and confirm that the change needed in `stattlepy/__init__.py` is fine.

**Comment by drewpinta** [comment]
I rebased and the change looks fine. By the way, here's the error I get without the change:

```
Traceback (most recent call last):
  File "myscript.py", line 3, in <module>
    from stattlepy import Stattleship
  File "/usr/local/lib/python3.5/site-packages/stattlepy/__init__.py", line 2, in <module>
    from Stattleship_API import Stattleship
ImportError: No module named 'Stattleship_API'
```

**Comment by dthyresson** [comment]
Thanks! Will :shipit:

**Comment by AdamMJenks** [comment]
Thanks for catching that, little oversight on my part for not using relative import

**Pull request merged**
